spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: local
---
spring:
  application:
    name: pq
  config:
    import:
      - classpath:secrets.yaml
