spring:
  application:
    name: pq
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${chunsik.db.url}:3306/pq
    username: ${chunsik.db.user}
    password: ${chunsik.db.password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${chunsik.mail.user}
    password: ${chunsik.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
auth-code-expiration-millis: 180000
server:
  port: 8080