spring:
  config:
    activate:
      on-profile: dev
  application:
    name: pq
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/pq
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect