spring:
  application:
    name: pq
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import:
      - optional:file:./src/main/resources/secrets.yaml
  datasource:
    url: jdbc:mysql://${chunsik.db.url}:3306/pq
    username: ${chunsik.db.user}
    password: ${chunsik.db.password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${chunsik.mail.user}
    password: ${chunsik.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
auth-code-expiration-millis: 180000
server:
  port: 8080

cloud:
  aws:
    s3:
      bucket: ${chunsik.s3.bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${chunsik.s3.access}
      secret-key: ${chunsik.s3.secret}

openai:
  api:
    key: ${chunsik.openai.key}