version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/prod/start.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/prod/cleanup.sh
      timeout: 120
