name: Develop PR Checks
run-name: PR checking
on:
  pull_request:
    types:
      - opened
    branches:
      - dev


env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: chunsik-deployments
  AWS_CODE_DEPLOY_APPLICATION: chunsik
  AWS_CODE_DEPLOY_GROUP: chunsik-dev-deploy

jobs:
  build-with-gradle:
    environment: dev
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_SECRET }}
          submodules: true

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 프로젝트 빌드
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: ./gradlew clean build -Dspring.profiles.active=dev