name: PR Checks
run-name: PR checking
on:
  pull_request:
    types: [ synchronize, opened, reopened, auto_merge_enabled ]
    branches:
      - dev
      - main
  workflow_dispatch:


env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: chunsik-deployments
  AWS_CODE_DEPLOY_APPLICATION: chunsik
  AWS_CODE_DEPLOY_GROUP: chunsik-dev-deploy

jobs:
  build-with-gradle:
    environment: dev
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_SECRET }}
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Buildx builder
        run: docker buildx create --use

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Jar 빌드
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: ./gradlew bootJar

      - name: Build Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform=linux/arm64 \
            .